# Specify version format
version: "1.0.0.{build}"

# Branches to build
branches:
  only: 
    - master

# Clone depth
clone_depth: 5

# Including commits with 'build' comment
only_commits:
  message: build

# Scripts that are called at very beginning, before repo cloning
init:
  - git config --global user.name "AppVeyor"
  - git config --global user.email "team@appveyor.com"
  - git config --global push.default simple
  - choco install doxygen.portable
  - choco install graphviz.portable
  - cmake --version

# Scripts that run after cloning repository
install:
  - git submodule update --init --recursive --remote

# Build scripts
build_script:
  - cd scripts
  - ./01-generate-VisualStudio.bat
  - ./02-build-VisualStudio.bat
  - ./03-tests.bat
  - ./04-install-VisualStudio.bat
  - ./05-doxygen-VisualStudio.bat
  - ./06-clean.bat

# Test scripts
test: off
