# Specify version format
version: "1.0.0.{build}"

# Branches to build
branches:
  only: 
    - master

# Clone depth
clone_depth: 5

# Including commits with 'build' comment
only_commits:
  message: build

# Build matrix
environment:
  matrix:
    - type: Cygwin
      build: C:\cygwin64\bin\bash -lc "cd $APPVEYOR_BUILD_FOLDER/build; exec 0</dev/null; ./cygwin.sh"
      command: C:\cygwin64\bin\bash -lc
    - type: MinGW
      build: call mingw.bat
      command: cmd /C
    - type: VisualStudio
      build: call vs.bat
      command: cmd /C

# Allow to fail on first error in matrix
matrix:
  fast_finish: true

# Scripts that are called at very beginning, before repo cloning
init:
  - ps: 'Start-FileDownload "http://cygwin.com/setup-x86_64.exe" -FileName "C:\cygwin64\setup-x86_64.exe"'
  - if "%type%"=="Cygwin" C:\cygwin64\setup-x86_64.exe --quiet-mode --no-shortcuts --upgrade-also --root "C:\cygwin64" --local-package-dir "C:\cygwin64\var\cache\setup" --packages cmake,automake,make,gcc-core,gcc-g++,doxygen,graphviz
  - if "%type%"=="MinGW" set PATH=%PATH:C:\Program Files\Git\usr\bin;=%;C:\tools\mingw64\bin
  - if "%type%"=="MinGW" choco install mingw
  - if "%type%"=="VisualStudio" set INCLUDE=C:\Program Files (x86)\Windows Kits\10\Include\10.0.14393.0\um;%INCLUDE%
  - if "%type%"=="VisualStudio" set LIB=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.14393.0\um\x64;%LIB%
  - choco install doxygen.portable
  - choco install graphviz.portable
  - '%command% "git config --global user.name "AppVeyor""'
  - '%command% "git config --global user.email "team@appveyor.com""'
  - '%command% "git config --global push.default simple"'

# Scripts that run after cloning repository
install:
  - git submodule update --init --recursive --remote

# Build scripts
build_script:
  - cd build
  - '%build%'

# Test scripts
test: off
