# Programming language definition
language: cpp

# Compilers
compiler:
  - gcc

# Operation systems
os:
  - linux

# Using Trusty environment
sudo: required
dist: trusty

# Add-ons and packages
addons:
  apt:
    packages:
      - cmake
      - doxygen
      - graphviz

# Branches to build
branches:
  only:
    - master

# Clone depth
git:
  depth: 5

# Scripts that run before install
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "travis@travis-ci.org"
  - git config --global push.default simple
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install doxygen; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install graphviz; fi
  - cmake --version

# Build scripts
script: 
  - cd scripts
  - ./01-generate-Unix.sh
  - ./02-build-Unix.sh
  - ./03-tests.sh
  - ./04-install-Unix.sh
  - ./05-doxygen-Unix.sh
  - ./06-clean.sh

# Don't send notifications on success
notifications:
  email:
    on_success: never
